name: Deploy

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add SSH key to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan 192.99.150.140 >> ~/.ssh/known_hosts

    - name: Copy files to VPS
      run: scp -r ./* administrator@192.99.150.140:/home/administrator/pro-ticket-frontend

    - name: Deploy with Docker Compose
      run: |
        ssh administrator@192.99.150.140 << 'EOF'
          cd /home/administrator/pro-ticket-frontend
          docker compose down
          docker rmi pro-ticket-frontend-server
          docker system prune -f
          docker compose up -d
        EOF
